print("Enter your first name:")
firstName_str = input()
firstName = str(firstName_str)
print("Enter your last name:")
lastName_str = input()
lastName = str(lastName_str)
print("Enter your age:")
age_str = input()
age = int(age_str)
print("Enter your weight:")
weight_str = input()
weight = float(weight_str)
print("Enter your height:")
height_str = input()
height = float(height_str)
print("Full Name:", firstName, lastName)
print("Age:", age)
print("Weight:", weight, "kg")
print("Height:", height, "m")

